import { readdirSync, statSync, writeFileSync } from 'node:fs';
import { join, relative, sep } from 'node:path';
import { defineConfig, type Plugin } from 'vitest/config';

function listFiles(dir: string): string[] {
  return readdirSync(dir).flatMap((name) => {
    const full = join(dir, name);
    return statSync(full).isDirectory() ? listFiles(full) : [full];
  });
}

/**
 * Emits a tiny hand-written service worker (no runtime dependency, ADR 0004):
 * every built file is precached on install, requests are served cache-first
 * and navigations fall back to the cached index.html, so the aquarium opens
 * offline after the first visit. The cache name carries a hash of the file
 * list, so a new build replaces the old cache on activate.
 */
function offlineWorker(): Plugin {
  let outDir = 'dist';
  return {
    name: 'akvariet-offline-worker',
    apply: 'build',
    configResolved(config) {
      outDir = config.build.outDir;
    },
    closeBundle() {
      const files = listFiles(outDir)
        .map((f) => relative(outDir, f).split(sep).join('/'))
        .filter((f) => f !== 'sw.js')
        .sort();
      const urls = ['./', ...files];
      let hash = 0;
      for (const ch of urls.join('|') + files.map((f) => statSync(join(outDir, f)).size).join(',')) {
        hash = (hash * 31 + ch.charCodeAt(0)) >>> 0;
      }
      const cache = `akvariet-${hash.toString(36)}`;
      const source = `// Generated by vite.config.ts – do not edit.
const CACHE = ${JSON.stringify(cache)};
const URLS = ${JSON.stringify(urls)};

self.addEventListener('install', (event) => {
  event.waitUntil(caches.open(CACHE).then((c) => c.addAll(URLS)).then(() => self.skipWaiting()));
});

self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches.keys()
      .then((keys) => Promise.all(keys.filter((k) => k !== CACHE).map((k) => caches.delete(k))))
      .then(() => self.clients.claim()),
  );
});

self.addEventListener('fetch', (event) => {
  const req = event.request;
  if (req.method !== 'GET' || new URL(req.url).origin !== location.origin) return;
  event.respondWith(
    caches.open(CACHE).then(async (cache) => {
      // ignoreVary: the dev/preview server and many hosts send "Vary: Origin", which would make module scripts miss.
      const hit = await cache.match(req, { ignoreSearch: true, ignoreVary: true });
      if (hit) return hit;
      try {
        return await fetch(req);
      } catch (err) {
        if (req.mode === 'navigate') {
          const page = await cache.match('./');
          if (page) return page;
        }
        throw err;
      }
    }),
  );
});
`;
      writeFileSync(join(outDir, 'sw.js'), source);
    },
  };
}

// `base: './' keeps asset paths relative so the build works under any
// GitHub Pages sub-path (https://<user>.github.io/akvariet/).
export default defineConfig({
  base: './',
  plugins: [offlineWorker()],
  build: { target: 'es2022', chunkSizeWarningLimit: 800 },
  test: { include: ['tests/**/*.test.ts'] },
});
